FROM node:slim

MAINTAINER alaxallves@gmail.com

RUN apt-get update && \
    curl -sL https://deb.nodesource.com/setup_7.x | bash - && \
    apt-get install -y nodejs tree libfontconfig bzip2 && \
    npm install --quiet --global vue-cli

RUN mkdir /Falko-2017.2-FrontEnd

COPY . /Falko-2017.2-FrontEnd

WORKDIR /Falko-2017.2-FrontEnd

COPY package.json /Falko-2017.2-FrontEnd/package.json

ENTRYPOINT npm

CMD ["install"]
CMD ["run","dev"]
